apiVersion: v1
kind: ConfigMap
metadata:
  name: hal-config
  labels:
    name: hal-config
data:
  MONGO_SERVERS: ""
  MONGO_USER: ""
  MONGO_DATABASE: ""
  MONGO_REPLICA_SET: ""
  MONGO_AUTH_SOURCE: ""
  MONGO_SSL: "0"
  NO_PROXY: ""


