apiVersion: v1
kind: ConfigMap
metadata:
  name: hal
  labels:
    name: hal
data:
  MONGO_SERVERS: pchop85.standardbank.co.za:27017,pchop86.standardbank.co.za:27017,pchop87.standardbank.co.za:27017
  MONGO_USER: chop
  MONGO_REPLICA_SET: humongo
  MONGO_AUTH_SOURCE: admin
  MONGO_SSL: "0"
  NO_PROXY: pchop85.standardbank.co.za,pchop86.standardbank.co.za,pchop87.standardbank.co.za,selenium.card-devops,easytrace-ha-test.standardbank.co.za,easytrace-dev.standardbank.co.za,dinerspbweb-dev.standardbank.co.za,dinerspbweb-sit.standardbank.co.za,skynet.standardbank.co.za,portal.sbic.co.za,tools.standardbank.co.za,pchfsvr1v.standardbank.co.za,selenium.card-devops
  SNMP_SERVER: ""
  SNMP_PORT: ""
  CALLOUT_URL: http://portal.sbic.co.za/callout/viewcallout.asp?View=Current&Team=Card+and+Payments+DevOps
  JIRA_TEMPLATE: '{ "fields": {  "project": {           "key": "CFEA"       },       "summary": "Non Prod - {{.Title}}",       "description": "{{.Description}}. Incident automatically created by HAL bot",       "issuetype": {          "name": "Bug"       },   "assignee": {"name": "{{.User}}"   }   }}'
  JIRA_DEFAULT_USER: a153527
  SKYNET_URL: https://skynet.standardbank.co.za
  SKYNET_USER: c1592023


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hal
  name: hal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal
  template:
    metadata:
      labels:
        app: hal
    spec:
      containers:
      - image: zamedic/go2hal:1.637.1
        name: hal
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 9162
          protocol: UDP
        envFrom:
        - configMapRef:
            name: hal
        - secretRef:
            name: hal
        env:
        - name: MONGO_DATABASE
          value: cardhaldev

---
kind: Service
apiVersion: v1
metadata:
  name: hal
spec:
  selector:
    app: hal
  ports:
  - protocol: TCP
    name: snmp
    port: 161
    targetPort: 9162
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hal
  annotations:
   kubernetes.io/ingress.class: istio
spec:
   rules:
     - host: cardhaldev.legion.sbsa.local
       http:
         paths:
           - backend:
               serviceName: hal
               servicePort: http
